apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "aeropredict.fullname" . }}-secrets
data:
  POSTGRES_PASSWORD: {{ .Values.env.POSTGRES_PASSWORD | default "Y2hhbmdlbWU=" | b64enc | quote }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.env.GRAFANA_ADMIN_PASSWORD | default "YWRtaW4=" | b64enc | quote }}
